services:
  - type: web
    name: ledger-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEFAULT_CURRENCY
        value: GHS
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SECRET_KEY
        generateValue: true
      - key: APP_PIN_HASH
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: Ledger Security <noreply@ledger.app>
